### ISSUE TITLE
페어 코드 리뷰

### ISSUE THREAD

**Issue by makepin2r** [gunhoray/MyToDoList#1]
안녕하세요! 작성하신 코드 잘 읽었습니다. 고생 많으셨습니다!
아래는 코드 리뷰 내용입니다. :)

1. App.jsx에서 addbtnHandler, deleteHander, donedeleteHander 함수에서 alert를 통해 입력값의 유효성을 체크하여 UX의 완성도를 높이신 부분이 좋았습니다. 다만 addbtnHander에서는 두 입력값이 모두 비었을 때만 확인하고, 나머지는 추가적인 if 없이 else 구문으로 대체해도 무방해보입니다. 두 번째 if 조건이 첫 if 조건에 부합하지 않은 모든 케이스와 동일해보입니다.
2. App.js의 completeHander, backtoprogress에서 find()로 수정할 값이 posts/doneposts에 존재하는지 검증 여부는 생략해도 좋을 듯 합니다. 이미 정상적으로 데이터를 받아 렌더링이 완료된 값의 데이터이기 때문에, 해당 단계에서는 유효하지 않은 값인지 확인하지 않아도 되겠다고 생각했습니다. 혹시 제가 고려하지 못한 케이스가 있다면 코멘트로 알려주시면 감사하겠습니다!
3. posts, doneposts를 나누지 않고 하나의 데이터로 관리하며, Inprogress, Completed에 전달할 때 isdone의 값을 기준으로 filter 하여 전달하면 데이터 중복을 방지하는 최적화가 가능해보입니다.
또한 이렇게 하나의 데이터로 통일하면 inprogress의 deleteHandler, donedeleteHander와 같이 동일한 로직을 가진 함수 또한 함께 통일이 가능하리라 생각합니다. 함수 내부에서 filter하는 대상 state가 같아지기 때문입니다!
4. 3번 항목에 이어, Inprogress와 Completed 컴포넌트 또한 동일한 기능과 UI를 가지고 있는 요소이므로 하나의 컴포넌트로 리팩토링하면 좋을 것 같습니다. 3에서 말씀드린 바와 같이 posts와 doneposts를 하나로 통일하여 delete 함수를 1개로 통일하고, completeHandler와 backtoprogress 함수 또한 동일한 로직이므로 대상 state를 하나로 합치고 타겟 데이터의 isdone을 ! 연산자를 활용하여 토글 형식으로 작성해주면 (ex. selectedPost.isdone = !selectedPost.isdone;) 하나의 함수로 통일할 수 있습니다.
5. 데이터의 내용이나 기능을 직관적으로 파악할 수 있는 변수명, 함수명을 사용하고자 노력하신 부분이 보여 아주 좋았습니다. 하지만 가독성을 위해 일관적인 Camel Case 사용으로 이름을 변경하시면 훨씬 가독성을 높일 수 있을 것 같습니다. (ex.  donedeleteHandler -> doneDeleteHander, backtoprogress -> backToProgress, selectedtodeleted -> selectedToDeleted)
6. components 폴더를 생성하여 프로젝트의 구조가 한눈에 보이게끔 하신 부분이 좋았습니다. 다만 컴포넌트 jsx 파일은 대문자로 시작하는 것이 좋을 것 같습니다. App.jsx와 같이 컴포넌트 명과 파일명을 일치하여 시작 문자를 대문자로 변경하면 더욱 가독성이 높아질 것이라 보입니다.

멋진 디자인과 꼼꼼함이 돋보이는 프로젝트였습니다!
감사합니다. 😊

**Comment by gunhoray** [comment]
Pure Gold 같은 리뷰와 조언들 너무 감사합니다~~!!
